#!/usr/bin/env bash

# author: steven, date: 2017.3.31
# routine for prompt

function prompt(){
if [ $# -ne 2 ]; then
return $_err_f_param_
fi

local prompts=$(map "$_env_c" get "env.cst")
[ -z "$prompts" ] && prompts=$(map init); prompts=$(map "$prompts" put "$1" "$2")
_swap_ "$prompts"
_env_c=$(map "$_env_c" put "env.cst" "$prompts")
}