#!/usr/bin/env bash

#author: steven, date: 2017.3.31

# routine for prompt
function hint(){
if [ $# -ne 2 ]; then # help tips
cat << HELP
hint is a command line prompt
usage: hint <key> <value>
HELP
return $_err_f_param_
fi

local hints=$(_dw_query "hint")
[ -z "$hints" ] && hints=$(map init)
hints=$(map "$hints" put "$1" "$2")
_dw_store "hint" "$hints"
}