#!/usr/bin/env bash

# author: steven, date: 2017.3.31
# tool suite increment loader

# search from cache
function ts_s(){
if [ $# -lt 1 ]; then # list all tools
_invoke_2c "ls" "$es_cache/ts"
return $_err_s_
fi
local r=$es_cache/ts/$1 && [ -d "$r" ] && echo $r
}

# tool suite loader routine
function ts(){
local order=${1:-""}

if [ -z "$order" ]; then # blank to call help
cat << HELP
ts is a tool suite increment loader
usage: ts <order> <args>
order: pck/trw
args: ....
HELP
return $_err_f_param_
fi

shift

# begin calculate, query current
local tss=$(_dw_query "ts:" $(map init))

# trw
if [ "trw" == "$order" ]; then
[ $# -ne 1 ] && return $(ts)
tss=$(map "$tss" del "$1")
fi

# pck
if [ "pck" == "$order" ]; then
[ $# -gt 1 -o -z "$1" ] && return $(ts)
local t=$(ts_s "$1")
if [ -n "$t" ]; then
tss=$(map "$tss" put "$1" "$t")
fi
fi

_dw_store "ts:" "$tss"
}