#!/bin/bash

# des install script
# author: steven, date:2017.3.31

# location calculate 
declare __anchor=${__anchor:=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)}

# main process
# ready go
source "$__anchor/builtin/desinit"
