#!/bin/bash

#author: steven, date:2017.3.31

# des load an init
# location calculate
declare atloc=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

#
# infrastructure
#
# path of des's root
function root(){
echo $atloc
}

# function to due with module's import
function include(){
if [ -f "$(root)/$1" ]; then
source $(root)/$1
fi
}

#
# main
#
# data for des
include "util/map.sh"
declare _des_ss_=$(map init) # _dw_ is a data pool in memeory cache
function _dw_purge(){
_des_ss_=$(map ${_des_ss_} del $@)
}
function _dw_store(){
_des_ss_=$(map ${_des_ss_} put $@)
}
function _dw_query(){
echo $(map ${_des_ss_} get $1)
}

# cli alias for des
for cli in $(ls $(root)/builtin/*.sh $(root)/*.sh 2> /dev/null); do
c=$(basename $cli); alias ${c%.sh}="source $cli"
done

# des ready
declare env_rp_path=${env_rp_path:=$PATH} && PATH=$env_rp_path:$(root)