#!/usr/bin/env bash

# author: steven, date: 2017.3.31
# sys's loop routine


_loop_c=$(queue init)

# event loop driver
function loop(){
local et
while true; do
if [ false = "$(queue "$_loop_c" empty)" ]; then
et=$(queue "$_loop_c" o); _loop_c=$(queue "$_loop_c" poll)
fi
done
}


# hatch event and dispatch
function hatch(){
_invoke_2c "_${1//:/_}loop"
}