#!/usr/bin/env bash

# author: steven, date:2017.4.12
# es's cl env init

_include "builtin/.loop"

# export
declare c
for c in $(_invoke_2c "ls $_root_/builtin"); do
_invoke_2c source "$_root_/builtin/$c"
done
