#!/bin/bash

# author: steven, date:2017.4.12
# es's cli

_include "etc/loop.cli.rc" && _invoke_2c "source $es_cache/etc/loop.cli.rc"

# restore point calc and restore point recover
_rp_envpath=${_rp_envpath:-"$PATH:$(_root)/builtin"} \
    && export PATH=${_rp_envpath}


# export cl
declare cli

for cli in $(_invoke_2c "ls $(_root)/builtin"); do
_invoke_2c "alias" "$cli=source $cli"
done

for cli in $(_invoke_2c "ls -A $(_root)/builtin | grep '^\..*'"); do
_invoke_2c "source $cli $(pwd)"
done
