#!/bin/bash

# author: steven, date:2017.4.12
# es's cli

_include "etc/loop.cli.rc" && _invoke_2c "source $es_cache/etc/loop.cli.rc"

# restore point calc
declare _rp_envpath=${_rp_envpath:-"$PATH:$(_root)/builtin"}

clis=$(_invoke_2c "ls -A $(_root)/builtin | grep '^\..*'")
for cli in $clis; do
_invoke_2c "source $(_root)/builtin/$cli $(pwd)"
done

# do restore point recover
export PATH=${_rp_envpath}