#!/bin/bash

# init script
# author: steven, date:2017.4.12
# process of es init

# es's root
function _root(){
echo $__anchor
}

# module's import relative to es's root
function _include(){
[ -f "$(_root)/$1" ] && source "$(_root)/$1"
}




# main process, start es
if [ -z "$(_root)" ]; then # env vaildate
return -1
fi

# es service first, then init cli env
_include "core/svc" && _include "core/escli"
