#!/usr/bin/env bash

# author: steven, date:2017.4.12
# process of es startup

# database for es's runtime
# which is based on forest data struct
# and ship with a pump
_dw_c=$(tree init)
# query op with a path
function _dw_query(){
[ $# -gt 2 ] && return $_err_f_param_
if [ 0 -eq $# ]; then
echo "$(tree "$_dw_c" trav)"; return $_err_s_
fi
local r=$(tree "$_dw_c" sel "$1") && echo "${r:-"$2"}"
}

# insert/update op
function _dw_store(){
[ $# -ne 2 ] && return $_err_f_param_
_dw_c=$(tree "$_dw_c" \
graft "$2" "$1" \
)
hatch "$1"
}

# delete op
function _dw_purge(){
[ $# -ne 1 ] && return $_err_f_param_ || _dw_store "$1" ""
}

# after service start,
# then resource config and init cli env
_include "core/svcs"
_include "es.rc"
_include "core/clenv"