#!/bin/bash

# author: steven, date: 2017.4.25
# const defination and routine

# error code
declare -i __err_f_param=3
declare -i __err_s_=0

# routine invoke with err ignore
function _invoke_2c(){
local c="$1" && shift && $c "$@" 2> /dev/null
}

# routine invoke with err and normal ignore
function _invoke_1c(){
local c="$1" && shift && $c "$@" > /dev/null 2>&1
}

# loop routine
# it is a temporary sln for event loop
function _loop(){
local c="$1_"
shift
_invoke_2c $c "$@"
}



# runtime data warehouse
_include "util/map.sh"
unset _dw_c && _dw_c=$(map init)

# select op
function _dw_query(){
[ $# -gt 2 ] && return $__err_f_param
local r=$(map $_dw_c get "$1")
echo ${r:-"$2"}
}
# delete op
function _dw_purge(){
[ $# -ne 1 ] && return $__err_f_param
_dw_c=$(map $_dw_c del "$1") && _loop "$1"
}
# insert or update op
function _dw_store(){
[ $# -ne 2 ] && return $__err_f_param
_dw_c=$(map $_dw_c put "$1" "$2") && _loop "$1"
}