#!/usr/bin/env bash

# load foundation framework
# author: steven, date:2018.3.18

# error code
declare -ir _err_f_param_=3
declare -ir _err_s_=0

# routine invoke with err ignore, it has a way round alias restrictions
function _invoke_2c(){
local routine=${1:-""}
local ref=$(alias "$routine" 2> /dev/null) && ref=${ref/*$routine=/} && ref=${ref//\'/}
[ ! -z "$ref" ] && unalias "$routine" 2> /dev/null
shift && $routine "$@" 2> /dev/null
[ ! -z "$ref" ] && alias "$routine=$ref" 2> /dev/null
}

# module's import relative to root
function _include(){
local module=${1:-""}
[ -f "$_root_/$module" ] && source "$_root_/$module"
}

_include "frw/inspect/assert"
_include "frw/util/tree"
_include "frw/net/net"

# loop routine
# it is a temporary sln for event loop
function _loop(){
local routine="_${1//:/_}loop" && shift && _invoke_2c $routine "$@"
}