#!/usr/bin/env bash

# load foundation framework
# author: steven, date:2018.3.18

# error code
declare -ir _err_f_param_=3
declare -ir _err_s_=0

# routine invoke with err ignore
function _invoke_2c(){
local c="$1" && shift && $c "$@" 2> /dev/null
}

# module's import relative to root
function _include(){
[ -f "$_root_/$1" ] && source "$_root_/$1"
}


_include "frw/util/tree"
_include "frw/util/stack"


# loop routine
# it is a temporary sln for event loop
function _loop(){
local c="_$1_loop" && shift && _invoke_2c $c "$@"
}