#!/bin/bash

# author: steven, date: 2017.4.25
# core const and routine

# error code
declare -i __err_f_param=3
declare -i __err_s_=0

# routine invoke with err ignore
function _invoke_2c(){
local c="$1" && shift && $c "$@" 2> /dev/null
}

# routine invoke with err and normal ignore
function _invoke_1c(){
local c="$1" && shift && $c "$@" > /dev/null 2>&1
}

# loop routine
# it is a temporary sln for event loop
function _loop(){
local c="$1_"
shift
_invoke_2c $c "$@"
}
