#!/bin/bash

# author: steven, date: 2017.3.31
# directory handle

# main routine
function d(){
if [ $# -lt 1 ]; then # help tips
cat << HELP
d is a directory command holder
usage: d <command> [path]
HELP
return $_err_f_param_
fi

local c=${1:-""}
_invoke_2c unalias "$c"; shift && $c "$@"; _invoke_2c alias "$c=d $c"
_dw_store "d" $c
}



_invoke_2c alias "cd=d cd"