#!/bin/bash

# init script
# author: steven, date:2017.4.12
# process of des init

# des's root
function _root(){
echo $__anchor
}

# module's import relative to des's root
function _include(){
[ -f "$(_root)/$1" ] && source "$(_root)/$1"
}


# main process
if [ -z "$(_root)" ]; then # env vaildate
return -1
fi
# restore point calc
declare _rp_envpath=${_rp_envpath:-$PATH}
# 1s start des core, 2s start service for des, 3s load cli of des
_include "builtin/core" && _include "builtin/svc" && _include "builtin/sh"
# do restore point recover
export PATH=${_rp_envpath}
